/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ReportFormRouteImport } from "./routes/report-form"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as MapRouteImport } from "./routes/map"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"

const ReportFormRoute = ReportFormRouteImport.update({
  id: "/report-form",
  path: "/report-form",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: "/map",
  path: "/map",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/login": typeof LoginRoute
  "/map": typeof MapRoute
  "/register": typeof RegisterRoute
  "/report-form": typeof ReportFormRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/login": typeof LoginRoute
  "/map": typeof MapRoute
  "/register": typeof RegisterRoute
  "/report-form": typeof ReportFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/login": typeof LoginRoute
  "/map": typeof MapRoute
  "/register": typeof RegisterRoute
  "/report-form": typeof ReportFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/about" | "/login" | "/map" | "/register" | "/report-form"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/login" | "/map" | "/register" | "/report-form"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/login"
    | "/map"
    | "/register"
    | "/report-form"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  RegisterRoute: typeof RegisterRoute
  ReportFormRoute: typeof ReportFormRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/report-form": {
      id: "/report-form"
      path: "/report-form"
      fullPath: "/report-form"
      preLoaderRoute: typeof ReportFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/map": {
      id: "/map"
      path: "/map"
      fullPath: "/map"
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  RegisterRoute: RegisterRoute,
  ReportFormRoute: ReportFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
